[phases.setup]
nixPkgs = ['python311', 'pip']
aptPkgs = ['python3-dev']

[phases.install] 
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Backend ready"']

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT'