[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 10
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"