[build]
nixpkgs = "https://github.com/NixOS/nixpkgs/archive/nixos-22.11.tar.gz"

[build.nixpacksPackages]
python = "3.11"

[deploy]
healthcheckPath = "/api/users"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 10
startCommand = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"

[env]
PORT = "8000"

# Tell Railway to only build the backend
[build.nixpacksBuildPhase]
nixpacksCommands = [
  "cd backend",
  "pip install -r requirements.txt"
]